// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LocalNorthwindEF.Views;

public partial class CategorySalesFor1997
{
    public string CategoryName { get; set; }

    public byte[] CategorySales { get; set; }
}