// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LocalNorthwindEF.Views;

public partial class SalesByCategory
{
    public int? CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string ProductName { get; set; }

    public byte[] ProductSales { get; set; }
}